model: MLP

data:
  task: VectorPVR

  train_params:
    size: 10.0e+1
    complexity: 2
    holdout: 1

  val_params:
    size: 10.0e+1
    complexity: 2
    holdout: 1
    adversarial: true

training:
  optimizer_type: SGD
  optimizer_params:
    lr: 0.05
    weight_decay: 1.0e-5
    momentum: 0.9

  schedular:
    num_warmup_epochs: 2

  batch_size: 2
  epochs: 4