model: MLP

data:
  task: VectorPVR

  train_params:
    size: 1.0e+4
    complexity: 2
    holdout: 1

  val_params:
    size: 1.0e+3
    complexity: 2
    holdout: 1
    adversarial: true

training:
  mixed_precision: false # 'mixed-precision training' improves performance
  val_check_interval: 1 # fraction of train epoch
  log_every_n_steps: 50 # default is 50

  optimizer_type: SGD
  optimizer_params:
    lr: 0.05
    weight_decay: 1.0e-5
    momentum: 0.9

  scheduler:
    num_warmup_epochs: 10

  batch_size: 16
  epochs: 200